l_english:
 com_topbar_configuration_button_tooltip: "Open Topbar Configuration"
 com_topbar_configuration_title: "Topbar Configuration"
 com_topbar_configuration_current: "Current Topbar"
 com_topbar_configuration_add: "Edit Topbar"
 com_topbar_configuration_always_show: "Always show topbar elements (#r Overlays windows#!)"
 com_topbar_configuration_add_explanation: "Add or remove topbar elements from the topbar using the buttons below."
 com_topbar_configuration_clear_first_tooltip: "Clear first topbar row."
 com_topbar_configuration_add_first_tooltip: "Add this element to the first topbar row."
 com_topbar_configuration_remove_first_tooltip: "Remove this element from the first topbar row."
 com_topbar_configuration_clear_second_tooltip: "Clear second topbar row."
 com_topbar_configuration_add_second_tooltip: "Add this element to the second topbar row."
 com_topbar_configuration_remove_second_tooltip: "Remove this element from the second topbar row."
 com_topbar_configuration_add_header_source: "Element Source"
 com_topbar_configuration_add_header_element: "Topbar Element"
 com_topbar_configuration_add_header_first: "First\nRow"
 com_topbar_configuration_add_header_second: "Second\nRow"